services:
  mysql:
    image: mysql:latest
    container_name: mysql_BDSastreria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "sastreria"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3305:3306"
    volumes:
      - "C:/Users/Jeimy/Desktop/BDSastreria_yml/mysql_data:/var/lib/mysql"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  mysql_data: